---

- name: Fetch avocado repos
  get_url:
    url: https://repos-avocadoproject.rhcloud.com/static/avocado-fedora.repo
    dest: /etc/yum.repos.d/avocado.repo
    mode: 0640

- name: Install avocado
  dnf: name=avocado state=latest

- name: Install avocado html plugin
  dnf: name=avocado-plugins-output-html state=latest
